cert-manager:
  ingressShim:
    defaultIssuerName: letsencrypt-production
    defaultIssuerKind: ClusterIssuer

clusterissuer:
  email: cloud@softwareunderground.org
  server: https://acme-v02.api.letsencrypt.org/directory
